### ISSUE TITLE
Notification UI bug

### ISSUE THREAD

**Issue by SnowTalking** [omnirom/android_device_motorola_sm6125_common#1]
A little hard to see the beginning of the new notification on the status bar because of the front facing cam, if you could fix this it would be great, thanks

![Screenshot_20210221-125816](https://user-images.githubusercontent.com/71605881/108633913-ed22a180-7444-11eb-8f5f-84bd08ab2a41.png)

**Comment by Vachounet** [comment]
As a note, when cutout overlay is not static, seems SystemUI trigger some aditional(s) event(s) (or some things happen later - after boot). As example, works fine when mainDisplayCutout is defined as a non-static rro overlay, and derped when static rro overlay or when defined in framework-res overlay.

**Comment by Vachounet** [comment]
https://gerrit.omnirom.org/c/android_frameworks_base/+/39274

**Comment by Vachounet** [comment]
Merged
