### ISSUE TITLE
Feature request & UI bug

### ISSUE THREAD

**Issue by SnowTalking** [omnirom/android_device_motorola_sm6125_common#2]
Ability to hide the gesture nav bar

Corners on the bottom left/right of the screen that shows the hint for assistant are not aligned correctly.

Thanks

How to test: 
Swipe up from gesture navbar to get the recent apps, may take a few tries as it doesn't always show up.

![IMG_20210221_155637](https://user-images.githubusercontent.com/71605881/108638691-611d7380-745e-11eb-92f6-170293ed5d14.jpg)

**Comment by Vachounet** [comment]
Need to adjust some overlays. @Hasaber8 already pinged me about that.

**Comment by Vachounet** [comment]
Merged
